In [1]:
import pandas as pd
import numpy as np
import random
from random import randint
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split, ShuffleSplit
from sklearn.datasets import make_regression
from autogluon.tabular import TabularDataset, TabularPredictor
from datetime import datetime

In [2]:
#materialData = pd.read_excel('Results_Impute/materialData_ii_imputed.xlsx')
materialData = pd.read_excel('Results_Impute/materialData_ii_imputed_text_numeric.xlsx')
materialData

,materialCategory,Category,MaterialType,materialDensity,materialConductivity,materialHeatCapacity
0,Glass,"Insulating material: Blanket and batt c, d",Glass-fiber batts,616.710841,0.20160,837.36000
1,Glass,"Insulating material: Blanket and batt c, d",Glass-fiber batts,7.849047,0.04680,1025.13798
2,Glass,"Insulating material: Blanket and batt c, d",Glass-fiber batts,10.892555,0.04176,1088.56800
3,Glass,"Insulating material: Blanket and batt c, d",Glass-fiber batts,13.135140,0.03816,1122.89976
4,Glass,"Insulating material: Blanket and batt c, d",Glass-fiber batts,22.425849,0.03312,1363.22208
...,...,...,...,...,...,...
250,Wood,Woods (12% moisture content) l: Hardwoods,"West coast woods, cedars",424.489280,0.11376,1840.51728
251,Wood,Woods (12% moisture content) l: Hardwoods,Eastern white cedar.,368.424658,0.12312,1836.33048
252,Wood,Woods (12% moisture content) l: Hardwoods,California redwood,416.480048,0.11232,1836.33048
253,Wood,Woods (12% moisture content) l: Hardwoods,Pine (oven-dried),368.424658,0.09216,1884.06000
254,Wood,Woods (12% moisture content) l: Hardwoods,Spruce (oven-dried),400.461585,0.09936,1884.06000

In [7]:
rs = ShuffleSplit(n_splits=1, test_size=0.25, random_state=0)  # n_splits=1 means we're doing one split

for train_index, test_index in rs.split(materialData):
    train_data = materialData.iloc[train_index]  
    test_data =materialData.iloc[test_index]
    
train_data.to_csv('trainESM.csv', index=False) 
test_data.to_csv('testESM.csv', index=False)

In [9]:
train_data.head()

,materialCategory,Category,MaterialType,materialDensity,materialConductivity,materialHeatCapacity
184,Cement,Masonry Materials: Concrete blocks h,"Lightweight aggregate (expanded shale, clay, s...",424.489280,0.113760,1840.51728
248,Wood,Woods (12% moisture content) l: Hardwoods,Spruce.,400.461585,0.114480,1843.02936
33,Polyisocyanurate,Insulating material: Board and slabs,"Polyisocyanurate with foil facers, aged 180 days",31.236004,0.022320,1580.93568
108,Rubber,Finish Flooring,Pile carpet with rubber pad3/8 - 1/2 in,288.332341,0.105926,1579.26096
156,Brick,Masonry Materials: Masonry units,"Brick, fired clay",1121.292438,0.403200,1055.07360

In [11]:
label = 'materialDensity'
train_data[label].describe()

count     191.000000
mean      768.646805
std       690.073957
min         7.208309
25%       352.406195
50%       560.646219
75%       977.126267
max      2883.323412
Name: materialDensity, dtype: float64

In [13]:
predictor = TabularPredictor(label=label, problem_type='regression').fit(train_data, 
                                                                         presets='best_quality', 
                                                                         hyperparameters='multimodal',#train more models
                                                                         time_limit=3600)

No path specified. Models will be saved in: "AutogluonModels\ag-20260330_084552"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.2
Python Version:     3.12.4
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26100
CPU Count:          32
Memory Avail:       7.49 GB / 31.71 GB (23.6%)
Disk Space Avail:   163.49 GB / 943.72 GB (17.3%)
===================================================
Presets specified: ['best_quality']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
2026-03-30 10:45:54,755	INFO util.py:154 -- Outdated packages:
  ipywidgets==7.8.1 found, needs ipywidgets>=8
Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2026-03-30 10:46:04,138	INFO worker.py:1810 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
		Context path: "C:\Users\20180031\Python_ASHRAE_Impute_Regression\AutogluonModels\ag-20260330_084552\ds_sub_fit\sub_fit_ho"
(_dystack pid=44076) Running DyStack sub-fit ...
(_dystack pid=44076) Beginning AutoGluon training ... Time limit = 878s
(_dystack pid=44076) AutoGluon will save models to "C:\Users\20180031\Python_ASHRAE_Impute_Regression\AutogluonModels\ag-20260330_084552\ds_sub_fit\sub_fit_ho"
(_dystack pid=44076) Train Data Rows:    169
(_dystack pid=44076) Train Data Columns: 5
(_dystack pid=44076) Label Column:       materialDensity
(_dystack pid=44076) Problem Type:       regression
(_dystack pid=44076) Preprocessing data ...
(_dystack pid=44076) Using Feature Generators to preprocess the data ...
(_dystack pid=44076) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=44076) 	Available Memory:                    7364.91 MB
(_dystack pid=44076) 	Train Data (Original)  Memory Usage: 0.04 MB (0.0% of available memory)
(_dystack pid=44076) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=44076) 	Stage 1 Generators:
(_dystack pid=44076) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=44076) 	Stage 2 Generators:
(_dystack pid=44076) 		Fitting FillNaFeatureGenerator...
(_dystack pid=44076) 	Stage 3 Generators:
(_dystack pid=44076) 		Fitting IdentityFeatureGenerator...
(_dystack pid=44076) 		Fitting IdentityFeatureGenerator...
(_dystack pid=44076) 			Fitting RenameFeatureGenerator...
(_dystack pid=44076) 		Fitting CategoryFeatureGenerator...
(_dystack pid=44076) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=44076) 		Fitting TextSpecialFeatureGenerator...
(_dystack pid=44076) 			Fitting BinnedFeatureGenerator...
(_dystack pid=44076) 			Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=44076) 		Fitting TextNgramFeatureGenerator...
(_dystack pid=44076) 			Fitting CountVectorizer for text features: ['Category', 'MaterialType']
(_dystack pid=44076) 			CountVectorizer fit with vocabulary size = 16
(_dystack pid=44076) 	Stage 4 Generators:
(_dystack pid=44076) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=44076) 	Stage 5 Generators:
(_dystack pid=44076) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=44076) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=44076) 		('float', [])        : 2 | ['materialConductivity', 'materialHeatCapacity']
(_dystack pid=44076) 		('object', [])       : 1 | ['materialCategory']
(_dystack pid=44076) 		('object', ['text']) : 2 | ['Category', 'MaterialType']
(_dystack pid=44076) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=44076) 		('category', [])                    :  1 | ['materialCategory']
(_dystack pid=44076) 		('category', ['text_as_category'])  :  2 | ['Category', 'MaterialType']
(_dystack pid=44076) 		('float', [])                       :  2 | ['materialConductivity', 'materialHeatCapacity']
(_dystack pid=44076) 		('int', ['binned', 'text_special']) : 24 | ['Category.char_count', 'Category.word_count', 'Category.capital_ratio', 'Category.lower_ratio', 'Category.digit_ratio', ...]
(_dystack pid=44076) 		('int', ['text_ngram'])             : 12 | ['__nlp__.and', '__nlp__.and siding', '__nlp__.board', '__nlp__.board and', '__nlp__.building', ...]
(_dystack pid=44076) 		('object', ['text'])                :  2 | ['Category_raw_text', 'MaterialType_raw_text']
(_dystack pid=44076) 	0.7s = Fit runtime
(_dystack pid=44076) 	5 features in original data used to generate 43 features in processed data.
(_dystack pid=44076) 	Train Data (Processed) Memory Usage: 0.04 MB (0.0% of available memory)
(_dystack pid=44076) Data preprocessing and feature engineering runtime = 0.7s ...
(_dystack pid=44076) AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
(_dystack pid=44076) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=44076) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=44076) User-specified model hyperparameters to be fit:
(_dystack pid=44076) {
(_dystack pid=44076) 	'NN_TORCH': [{}],
(_dystack pid=44076) 	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=44076) 	'CAT': [{}],
(_dystack pid=44076) 	'XGB': [{}],
(_dystack pid=44076) 	'AG_AUTOMM': [{}],
(_dystack pid=44076) 	'VW': [{}],
(_dystack pid=44076) }
(_dystack pid=44076) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=44076) Fitting 8 L1 models, fit_strategy="sequential" ...
(_dystack pid=44076) Fitting model: LightGBM_BAG_L1 ... Training model for up to 584.50s of the 876.97s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.11%)

(_ray_fit pid=43576) [1000]	valid_set's rmse: 147.768

(_dystack pid=44076) 	-164.0488	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	6.46s	 = Training   runtime
(_dystack pid=44076) 	0.07s	 = Validation runtime
(_dystack pid=44076) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 560.54s of the 853.01s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.14%)

(_ray_fit pid=46044) [1000]	valid_set's rmse: 139.339
(_ray_fit pid=51168) [1000]	valid_set's rmse: 119.918

(_dystack pid=44076) 	-170.5905	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	4.84s	 = Training   runtime
(_dystack pid=44076) 	0.07s	 = Validation runtime
(_dystack pid=44076) Fitting model: CatBoost_BAG_L1 ... Training model for up to 546.57s of the 839.04s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.30%)
(_ray_fit pid=51020) 	Ran out of time, early stopping on iteration 3838.
(_dystack pid=44076) 	-164.1113	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	437.27s	 = Training   runtime
(_dystack pid=44076) 	0.14s	 = Validation runtime
(_dystack pid=44076) Fitting model: XGBoost_BAG_L1 ... Training model for up to 100.35s of the 392.82s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.27%)
(_dystack pid=44076) 	-173.0976	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	9.03s	 = Training   runtime
(_dystack pid=44076) 	0.1s	 = Validation runtime
(_dystack pid=44076) Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 82.13s of the 374.59s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.01%)
(_dystack pid=44076) 	Warning: Exception caused NeuralNetTorch_BAG_L1 to fail during training... Skipping this model.
(_dystack pid=44076) 		ray::_ray_fit() (pid=36316, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 201, in _fit
(_dystack pid=44076)     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)
(_dystack pid=44076)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 669, in _generate_dataset
(_dystack pid=44076)     dataset = self._process_train_data(
(_dystack pid=44076)               ^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 734, in _process_train_data
(_dystack pid=44076)     self.processor = create_preprocessor(
(_dystack pid=44076)                      ^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\utils\data_preprocessor.py", line 40, in create_preprocessor
(_dystack pid=44076)     return ColumnTransformer(
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^
(_dystack pid=44076) TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'
(_dystack pid=44076) Detailed Traceback:
(_dystack pid=44076) Traceback (most recent call last):
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2106, in _train_and_save
(_dystack pid=44076)     model = self._train_single(**model_fit_kwargs)
(_dystack pid=44076)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 1993, in _train_single
(_dystack pid=44076)     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
(_dystack pid=44076)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\stacker_ensemble_model.py", line 270, in _fit
(_dystack pid=44076)     return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 298, in _fit
(_dystack pid=44076)     self._fit_folds(
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 724, in _fit_folds
(_dystack pid=44076)     fold_fitting_strategy.after_all_folds_scheduled()
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 690, in after_all_folds_scheduled
(_dystack pid=44076)     self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 631, in _run_parallel
(_dystack pid=44076)     self._process_fold_results(finished, unfinished, fold_ctx)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 587, in _process_fold_results
(_dystack pid=44076)     raise processed_exception
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 550, in _process_fold_results
(_dystack pid=44076)     fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size, fit_num_cpus, fit_num_gpus = self.ray.get(finished)
(_dystack pid=44076)                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
(_dystack pid=44076)     return fn(*args, **kwargs)
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
(_dystack pid=44076)     return func(*args, **kwargs)
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\worker.py", line 2753, in get
(_dystack pid=44076)     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
(_dystack pid=44076)                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\worker.py", line 904, in get_objects
(_dystack pid=44076)     raise value.as_instanceof_cause()
(_dystack pid=44076) ray.exceptions.RayTaskError(TypeError): ray::_ray_fit() (pid=36316, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 201, in _fit
(_dystack pid=44076)     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)
(_dystack pid=44076)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 669, in _generate_dataset
(_dystack pid=44076)     dataset = self._process_train_data(
(_dystack pid=44076)               ^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 734, in _process_train_data
(_dystack pid=44076)     self.processor = create_preprocessor(
(_dystack pid=44076)                      ^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\utils\data_preprocessor.py", line 40, in create_preprocessor
(_dystack pid=44076)     return ColumnTransformer(
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^
(_dystack pid=44076) TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'
(_dystack pid=44076) Fitting model: VowpalWabbit_BAG_L1 ... Training model for up to 62.81s of the 355.27s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.01%)
(_dystack pid=44076) 	Warning: Exception caused VowpalWabbit_BAG_L1 to fail during training (ImportError)... Skipping this model.
(_dystack pid=44076) 		ray::_ray_fit() (pid=50972, ip=127.0.0.1)
(_dystack pid=44076) ModuleNotFoundError: No module named 'vowpalwabbit'
(_dystack pid=44076)
(_dystack pid=44076) During handling of the above exception, another exception occurred:
(_dystack pid=44076)
(_dystack pid=44076) ray::_ray_fit() (pid=50972, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1856, in ray._raylet.execute_task
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1957, in ray._raylet.execute_task
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\vowpalwabbit\vowpalwabbit_model.py", line 73, in _fit
(_dystack pid=44076)     try_import_vowpalwabbit()
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\common\utils\try_import.py", line 205, in try_import_vowpalwabbit
(_dystack pid=44076)     raise ImportError(
(_dystack pid=44076) ImportError: `import vowpalwabbit` failed.
(_dystack pid=44076) A quick tip is to install via `pip install vowpalwabbit>=9,<9.10
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_ray_fit() (pid=21972, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 201, in _fit
(_dystack pid=44076)     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)
(_dystack pid=44076)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 669, in _generate_dataset
(_dystack pid=44076)     dataset = self._process_train_data(
(_dystack pid=44076)               ^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 734, in _process_train_data
(_dystack pid=44076)     self.processor = create_preprocessor(
(_dystack pid=44076)                      ^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\utils\data_preprocessor.py", line 40, in create_preprocessor
(_dystack pid=44076)     return ColumnTransformer(
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^
(_dystack pid=44076) TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_ray_fit() (pid=50272, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 201, in _fit
(_dystack pid=44076)     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)
(_dystack pid=44076)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 669, in _generate_dataset
(_dystack pid=44076)     dataset = self._process_train_data(
(_dystack pid=44076)               ^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 734, in _process_train_data
(_dystack pid=44076)     self.processor = create_preprocessor(
(_dystack pid=44076)                      ^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\utils\data_preprocessor.py", line 40, in create_preprocessor
(_dystack pid=44076)     return ColumnTransformer(
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^
(_dystack pid=44076) TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_ray_fit() (pid=29344, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 201, in _fit
(_dystack pid=44076)     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)
(_dystack pid=44076)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 669, in _generate_dataset
(_dystack pid=44076)     dataset = self._process_train_data(
(_dystack pid=44076)               ^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 734, in _process_train_data
(_dystack pid=44076)     self.processor = create_preprocessor(
(_dystack pid=44076)                      ^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\utils\data_preprocessor.py", line 40, in create_preprocessor
(_dystack pid=44076)     return ColumnTransformer(
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^
(_dystack pid=44076) TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_ray_fit() (pid=27884, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^

(_ray_fit pid=40748) [1000]	valid_set's rmse: 89.6591 [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_ray_fit pid=53824) [5000]	valid_set's rmse: 207.559 [repeated 5x across cluster]
(_ray_fit pid=53824) [9000]	valid_set's rmse: 207.559 [repeated 4x across cluster]

(_dystack pid=44076) 	-174.9105	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	28.63s	 = Training   runtime
(_dystack pid=44076) 	0.1s	 = Validation runtime
(_dystack pid=44076) Fitting model: MultiModalPredictor_BAG_L1 ... Training model for up to 14.43s of the 306.90s of remaining time.
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_ray_fit() (pid=39188, ip=127.0.0.1)
(_dystack pid=44076) ModuleNotFoundError: No module named 'vowpalwabbit'
(_dystack pid=44076)
(_dystack pid=44076) During handling of the above exception, another exception occurred:
(_dystack pid=44076)
(_dystack pid=44076) ray::_ray_fit() (pid=39188, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1856, in ray._raylet.execute_task
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1957, in ray._raylet.execute_task
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\vowpalwabbit\vowpalwabbit_model.py", line 73, in _fit
(_dystack pid=44076)     try_import_vowpalwabbit()
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\common\utils\try_import.py", line 205, in try_import_vowpalwabbit
(_dystack pid=44076)     raise ImportError(
(_dystack pid=44076) ImportError: `import vowpalwabbit` failed.
(_dystack pid=44076) A quick tip is to install via `pip install vowpalwabbit>=9,<9.10
(_dystack pid=44076) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
(_dystack pid=44076) 2026-03-30 10:56:52.824597: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
(_dystack pid=44076) 2026-03-30 10:57:01.265822: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
(_dystack pid=44076) 	Warning: Exception caused MultiModalPredictor_BAG_L1 to fail during training... Skipping this model.
(_dystack pid=44076) 		The total system num_gpus=0 is less than minimum num_gpus=1 to fit StackerEnsembleModel. Consider using a machine with more GPUs.
(_dystack pid=44076) Detailed Traceback:
(_dystack pid=44076) Traceback (most recent call last):
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2106, in _train_and_save
(_dystack pid=44076)     model = self._train_single(**model_fit_kwargs)
(_dystack pid=44076)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 1993, in _train_single
(_dystack pid=44076)     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
(_dystack pid=44076)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 914, in fit
(_dystack pid=44076)     kwargs = self._preprocess_fit_args(**kwargs)
(_dystack pid=44076)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 566, in _preprocess_fit_args
(_dystack pid=44076)     kwargs = self._preprocess_fit_resources(**kwargs)
(_dystack pid=44076)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 816, in _preprocess_fit_resources
(_dystack pid=44076)     return self._calculate_total_resources(silent=silent, total_resources=total_resources, parallel_hpo=parallel_hpo, **kwargs)
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 758, in _calculate_total_resources
(_dystack pid=44076)     system_num_gpus >= minimum_model_num_gpus
(_dystack pid=44076) AssertionError: The total system num_gpus=0 is less than minimum num_gpus=1 to fit StackerEnsembleModel. Consider using a machine with more GPUs.
(_dystack pid=44076) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 220.41s of remaining time.
(_dystack pid=44076) 	Ensemble Weights: {'CatBoost_BAG_L1': 0.458, 'LightGBM_BAG_L1': 0.417, 'XGBoost_BAG_L1': 0.125}
(_dystack pid=44076) 	-151.1019	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	0.03s	 = Training   runtime
(_dystack pid=44076) 	0.0s	 = Validation runtime
(_dystack pid=44076) Fitting 6 L2 models, fit_strategy="sequential" ...
(_dystack pid=44076) Fitting model: LightGBM_BAG_L2 ... Training model for up to 220.32s of the 220.31s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.18%)
(_dystack pid=44076) 	-169.6481	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	4.78s	 = Training   runtime
(_dystack pid=44076) 	0.07s	 = Validation runtime
(_dystack pid=44076) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 205.99s of the 205.98s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.23%)

(_ray_fit pid=53664) [1000]	valid_set's rmse: 215.603 [repeated 2x across cluster]

(_dystack pid=44076) 	-175.7773	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	4.85s	 = Training   runtime
(_dystack pid=44076) 	0.07s	 = Validation runtime
(_dystack pid=44076) Fitting model: CatBoost_BAG_L2 ... Training model for up to 191.32s of the 191.31s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.43%)
(_dystack pid=44076) 	-182.4332	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	120.6s	 = Training   runtime
(_dystack pid=44076) 	0.12s	 = Validation runtime
(_dystack pid=44076) Fitting model: XGBoost_BAG_L2 ... Training model for up to 57.50s of the 57.48s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.29%)
(_dystack pid=44076) 	-202.8716	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	8.32s	 = Training   runtime
(_dystack pid=44076) 	0.09s	 = Validation runtime
(_dystack pid=44076) Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 38.14s of the 38.13s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.01%)
(_dystack pid=44076) 	Warning: Exception caused NeuralNetTorch_BAG_L2 to fail during training... Skipping this model.
(_dystack pid=44076) 		ray::_ray_fit() (pid=46784, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 201, in _fit
(_dystack pid=44076)     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)
(_dystack pid=44076)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 669, in _generate_dataset
(_dystack pid=44076)     dataset = self._process_train_data(
(_dystack pid=44076)               ^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 734, in _process_train_data
(_dystack pid=44076)     self.processor = create_preprocessor(
(_dystack pid=44076)                      ^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\utils\data_preprocessor.py", line 40, in create_preprocessor
(_dystack pid=44076)     return ColumnTransformer(
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^
(_dystack pid=44076) TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'
(_dystack pid=44076) Detailed Traceback:
(_dystack pid=44076) Traceback (most recent call last):
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2106, in _train_and_save
(_dystack pid=44076)     model = self._train_single(**model_fit_kwargs)
(_dystack pid=44076)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 1993, in _train_single
(_dystack pid=44076)     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
(_dystack pid=44076)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\stacker_ensemble_model.py", line 270, in _fit
(_dystack pid=44076)     return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 298, in _fit
(_dystack pid=44076)     self._fit_folds(
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 724, in _fit_folds
(_dystack pid=44076)     fold_fitting_strategy.after_all_folds_scheduled()
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 690, in after_all_folds_scheduled
(_dystack pid=44076)     self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 631, in _run_parallel
(_dystack pid=44076)     self._process_fold_results(finished, unfinished, fold_ctx)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 587, in _process_fold_results
(_dystack pid=44076)     raise processed_exception
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 550, in _process_fold_results
(_dystack pid=44076)     fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size, fit_num_cpus, fit_num_gpus = self.ray.get(finished)
(_dystack pid=44076)                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
(_dystack pid=44076)     return fn(*args, **kwargs)
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
(_dystack pid=44076)     return func(*args, **kwargs)
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\worker.py", line 2753, in get
(_dystack pid=44076)     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
(_dystack pid=44076)                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\worker.py", line 904, in get_objects
(_dystack pid=44076)     raise value.as_instanceof_cause()
(_dystack pid=44076) ray.exceptions.RayTaskError(TypeError): ray::_ray_fit() (pid=46784, ip=127.0.0.1)
(_dystack pid=44076)   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
(_dystack pid=44076)     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
(_dystack pid=44076)     out = self._fit(**kwargs)
(_dystack pid=44076)           ^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 201, in _fit
(_dystack pid=44076)     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)
(_dystack pid=44076)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 669, in _generate_dataset
(_dystack pid=44076)     dataset = self._process_train_data(
(_dystack pid=44076)               ^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 734, in _process_train_data
(_dystack pid=44076)     self.processor = create_preprocessor(
(_dystack pid=44076)                      ^^^^^^^^^^^^^^^^^^^^
(_dystack pid=44076)   File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\utils\data_preprocessor.py", line 40, in create_preprocessor
(_dystack pid=44076)     return ColumnTransformer(
(_dystack pid=44076)            ^^^^^^^^^^^^^^^^^^
(_dystack pid=44076) TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'
(_dystack pid=44076) Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 16.20s of the 16.18s of remaining time.
(_dystack pid=44076) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.90%)

(_ray_fit pid=36032) [1000]	valid_set's rmse: 93.6024
(_ray_fit pid=9340) [1000]	valid_set's rmse: 218.432
(_ray_fit pid=9340) [2000]	valid_set's rmse: 217.514
(_ray_fit pid=9340) [3000]	valid_set's rmse: 217.346
(_ray_fit pid=9340) [4000]	valid_set's rmse: 217.311
(_ray_fit pid=9340) [5000]	valid_set's rmse: 217.304
(_ray_fit pid=9340) [6000]	valid_set's rmse: 217.303
(_ray_fit pid=9340) [7000]	valid_set's rmse: 217.303
(_ray_fit pid=9340) [8000]	valid_set's rmse: 217.303

(_ray_fit pid=9340) 	Ran out of time, early stopping on iteration 8308. Best iteration is:
(_ray_fit pid=9340) 	[8308]	valid_set's rmse: 217.303
(_dystack pid=44076) 	-182.9824	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	20.11s	 = Training   runtime
(_dystack pid=44076) 	0.1s	 = Validation runtime
(_dystack pid=44076) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the -15.69s of remaining time.
(_dystack pid=44076) 	Ensemble Weights: {'CatBoost_BAG_L1': 0.458, 'LightGBM_BAG_L1': 0.417, 'XGBoost_BAG_L1': 0.125}
(_dystack pid=44076) 	-151.1019	 = Validation score   (-root_mean_squared_error)
(_dystack pid=44076) 	0.02s	 = Training   runtime
(_dystack pid=44076) 	0.0s	 = Validation runtime
(_dystack pid=44076) AutoGluon training complete, total runtime = 893.46s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 70.5 rows/s (22 batch size)
(_dystack pid=44076) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("C:\Users\20180031\Python_ASHRAE_Impute_Regression\AutogluonModels\ag-20260330_084552\ds_sub_fit\sub_fit_ho")
(_dystack pid=44076) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                   model  score_holdout   score_val              eval_metric  pred_time_test  pred_time_val    fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0        LightGBM_BAG_L2    -111.911382 -169.648118  root_mean_squared_error       12.718678       0.379242  457.541803                 1.043683                0.067324           4.776541            2       True          7
1        LightGBM_BAG_L1    -125.028759 -164.048823  root_mean_squared_error        3.705340       0.069017    6.463079                 3.705340                0.069017           6.463079            1       True          1
2    WeightedEnsemble_L3    -125.663902 -151.101897  root_mean_squared_error       11.731131       0.312813  452.783461                 0.056136                0.000894           0.018199            3       True         12
3    WeightedEnsemble_L2    -125.663902 -151.101897  root_mean_squared_error       11.755781       0.312928  452.793098                 0.080786                0.001010           0.027837            2       True          6
4        CatBoost_BAG_L2    -125.678212 -182.433179  root_mean_squared_error       13.931461       0.436429  573.366353                 2.256466                0.124510         120.601091            2       True          9
5   LightGBMLarge_BAG_L2    -128.037393 -182.982379  root_mean_squared_error       13.641096       0.413356  472.878032                 1.966101                0.101437          20.112771            2       True         11
6         XGBoost_BAG_L2    -129.745471 -202.871559  root_mean_squared_error       15.992557       0.406662  461.086897                 4.317562                0.094743           8.321636            2       True         10
7      LightGBMXT_BAG_L2    -132.439953 -175.777252  root_mean_squared_error       12.710639       0.380123  457.620178                 1.035644                0.068204           4.854917            2       True          8
8        CatBoost_BAG_L1    -139.765136 -164.111343  root_mean_squared_error        1.481625       0.144231  437.268228                 1.481625                0.144231         437.268228            1       True          3
9         XGBoost_BAG_L1    -142.191796 -173.097620  root_mean_squared_error        6.488030       0.098671    9.033955                 6.488030                0.098671           9.033955            1       True          4
10  LightGBMLarge_BAG_L1    -150.414360 -174.910525  root_mean_squared_error        1.807387       0.101376   28.634547                 1.807387                0.101376          28.634547            1       True          5
11     LightGBMXT_BAG_L1    -156.866305 -170.590469  root_mean_squared_error        1.168544       0.073206    4.840182                 1.168544                0.073206           4.840182            1       True          2
	1	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)
	959s	 = DyStack   runtime |	2641s	 = Remaining runtime
Starting main fit with num_stack_levels=1.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`
Beginning AutoGluon training ... Time limit = 2641s
AutoGluon will save models to "C:\Users\20180031\Python_ASHRAE_Impute_Regression\AutogluonModels\ag-20260330_084552"
Train Data Rows:    191
Train Data Columns: 5
Label Column:       materialDensity
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5741.93 MB
	Train Data (Original)  Memory Usage: 0.04 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting IdentityFeatureGenerator...
			Fitting RenameFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['Category', 'MaterialType']
			CountVectorizer fit with vocabulary size = 16
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 2 | ['materialConductivity', 'materialHeatCapacity']
		('object', [])       : 1 | ['materialCategory']
		('object', ['text']) : 2 | ['Category', 'MaterialType']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :  1 | ['materialCategory']
		('category', ['text_as_category'])  :  2 | ['Category', 'MaterialType']
		('float', [])                       :  2 | ['materialConductivity', 'materialHeatCapacity']
		('int', ['binned', 'text_special']) : 24 | ['Category.char_count', 'Category.word_count', 'Category.capital_ratio', 'Category.lower_ratio', 'Category.digit_ratio', ...]
		('int', ['text_ngram'])             : 13 | ['__nlp__.and', '__nlp__.and siding', '__nlp__.board', '__nlp__.board and', '__nlp__.building', ...]
		('object', ['text'])                :  2 | ['Category_raw_text', 'MaterialType_raw_text']
	0.7s = Fit runtime
	5 features in original data used to generate 44 features in processed data.
	Train Data (Processed) Memory Usage: 0.04 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.72s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'AG_AUTOMM': [{}],
	'VW': [{}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 8 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1759.73s of the 2640.25s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.14%)
	-147.7424	 = Validation score   (-root_mean_squared_error)
	5.84s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1736.37s of the 2616.89s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.12%)
	-156.2633	 = Validation score   (-root_mean_squared_error)
	8.39s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 1718.01s of the 2598.53s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.25%)
	-159.8669	 = Validation score   (-root_mean_squared_error)
	1374.8s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 334.40s of the 1214.92s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.29%)
	-163.2099	 = Validation score   (-root_mean_squared_error)
	8.5s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 316.40s of the 1196.92s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.01%)
	Warning: Exception caused NeuralNetTorch_BAG_L1 to fail during training... Skipping this model.
		ray::_ray_fit() (pid=1888, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 201, in _fit
    train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 669, in _generate_dataset
    dataset = self._process_train_data(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 734, in _process_train_data
    self.processor = create_preprocessor(
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\utils\data_preprocessor.py", line 40, in create_preprocessor
    return ColumnTransformer(
           ^^^^^^^^^^^^^^^^^^
TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'
Detailed Traceback:
Traceback (most recent call last):
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2106, in _train_and_save
    model = self._train_single(**model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 1993, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\stacker_ensemble_model.py", line 270, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 298, in _fit
    self._fit_folds(
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 724, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 690, in after_all_folds_scheduled
    self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 631, in _run_parallel
    self._process_fold_results(finished, unfinished, fold_ctx)
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 587, in _process_fold_results
    raise processed_exception
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 550, in _process_fold_results
    fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size, fit_num_cpus, fit_num_gpus = self.ray.get(finished)
                                                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\worker.py", line 2753, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\ray\_private\worker.py", line 904, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::_ray_fit() (pid=1888, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 201, in _fit
    train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 669, in _generate_dataset
    dataset = self._process_train_data(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 734, in _process_train_data
    self.processor = create_preprocessor(
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\tabular_nn\utils\data_preprocessor.py", line 40, in create_preprocessor
    return ColumnTransformer(
           ^^^^^^^^^^^^^^^^^^
TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'
Fitting model: VowpalWabbit_BAG_L1 ... Training model for up to 295.96s of the 1176.48s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.00%)
2026-03-30 11:26:21,428	ERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2026-03-30 11:26:21,438	ERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2026-03-30 11:26:21,447	ERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
	Warning: Exception caused VowpalWabbit_BAG_L1 to fail during training (ImportError)... Skipping this model.
		ray::_ray_fit() (pid=45004, ip=127.0.0.1)
ModuleNotFoundError: No module named 'vowpalwabbit'

During handling of the above exception, another exception occurred:

ray::_ray_fit() (pid=45004, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1856, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1957, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 413, in _ray_fit
    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925, in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\tabular\models\vowpalwabbit\vowpalwabbit_model.py", line 73, in _fit
    try_import_vowpalwabbit()
  File "C:\Users\20180031\AppData\Local\anaconda3\Lib\site-packages\autogluon\common\utils\try_import.py", line 205, in try_import_vowpalwabbit
    raise ImportError(
ImportError: `import vowpalwabbit` failed.
A quick tip is to install via `pip install vowpalwabbit>=9,<9.10
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 286.17s of the 1166.69s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=4, gpus=0, memory=0.69%)
2026-03-30 11:26:30,532	ERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2026-03-30 11:26:30,539	ERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2026-03-30 11:26:30,545	ERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.

In [24]:
results = predictor.fit_summary()

*** Summary of fit() ***
Estimated performance of each model:
                    model   score_val              eval_metric  pred_time_val    fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0     WeightedEnsemble_L3 -133.961527  root_mean_squared_error       0.440394  297.174134                0.000979           0.008021            3       True         14
1     WeightedEnsemble_L2 -134.509990  root_mean_squared_error       0.253796  283.624825                0.000000           0.008992            2       True          7
2         LightGBM_BAG_L1 -147.742419  root_mean_squared_error       0.023510    2.268571                0.023510           2.268571            1       True          1
3    LightGBMLarge_BAG_L1 -152.085484  root_mean_squared_error       0.023510    2.751824                0.023510           2.751824            1       True          6
4         CatBoost_BAG_L1 -157.511912  root_mean_squared_error       0.033631  261.414557                0.033631         261.414557            1       True          3
5          XGBoost_BAG_L2 -157.688283  root_mean_squared_error       0.289535  284.652256                0.035739           1.036423            2       True         11
6       LightGBMXT_BAG_L1 -158.195122  root_mean_squared_error       0.024009    4.883698                0.024009           4.883698            1       True          2
7    LightGBMLarge_BAG_L2 -160.576227  root_mean_squared_error       0.274940  285.430039                0.021144           1.814206            2       True         13
8       LightGBMXT_BAG_L2 -162.801794  root_mean_squared_error       0.275303  284.696770                0.021508           1.080937            2       True          9
9          XGBoost_BAG_L1 -164.574959  root_mean_squared_error       0.034101    1.271794                0.034101           1.271794            1       True          4
10        LightGBM_BAG_L2 -166.712646  root_mean_squared_error       0.277869  284.318681                0.024073           0.702847            2       True          8
11        CatBoost_BAG_L2 -170.018267  root_mean_squared_error       0.281767  392.512489                0.027972         108.896656            2       True         10
12  NeuralNetTorch_BAG_L2 -175.164032  root_mean_squared_error       0.382532  294.315484                0.128736          10.699651            2       True         12
13  NeuralNetTorch_BAG_L1 -214.508005  root_mean_squared_error       0.115035   11.025389                0.115035          11.025389            1       True          5
Number of models trained: 14
Types of models trained:
{'StackerEnsembleModel_TabularNeuralNetTorch', 'WeightedEnsembleModel', 'StackerEnsembleModel_XGBoost', 'StackerEnsembleModel_LGB', 'StackerEnsembleModel_CatBoost'}
Bagging used: True  (with 8 folds)
Multi-layer stack-ensembling used: True  (with 3 levels)
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', ['text_as_category'])  :  2 | ['materialCategory', 'materialDescription']
('float', [])                       :  2 | ['materialConductivity', 'materialHeatCapacity']
('int', ['binned', 'text_special']) : 24 | ['materialCategory.char_count', 'materialCategory.word_count', 'materialCategory.capital_ratio', 'materialCategory.lower_ratio', 'materialCategory.digit_ratio', ...]
('int', ['text_ngram'])             : 13 | ['__nlp__.and', '__nlp__.and siding', '__nlp__.board', '__nlp__.board and', '__nlp__.building', ...]
('object', ['text'])                :  2 | ['materialCategory_raw_text', 'materialDescription_raw_text']
*** End of fit() summary ***

C:\Users\20180031\AppData\Local\anaconda3\envs\myenv\lib\site-packages\autogluon\core\utils\plots.py:169: UserWarning: AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"
  warnings.warn('AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"')

In [14]:
test_data = TabularDataset('testESM.csv')

Loaded data from: testESM.csv | Columns = 5 / 5 | Rows = 64 -> 64

In [34]:
Y_test = test_data['materialDensity']

In [36]:
test_data.head()

,materialCategory,materialDescription,materialDensity,materialConductivity,materialHeatCapacity
0,Masonry Materials: Masonry units,"Clay tile, hollow 1 cell deep 4 in",424.489280,0.11376,1840.51728
1,Building Board and Siding: Board,Waferboard,592.683146,0.09072,1884.06000
2,Masonry Materials: Concrete blocks h,Normal-weight aggregate (sand and gravel) 8 in...,424.489280,0.11376,1840.51728
3,Building Board and Siding: Siding,"Aluminum, steel, or vinyl k over sheathing ins...",424.489280,0.11376,1840.51728
4,Masonry Materials: Masonry units,"Brick, fired clay",2082.400242,1.02240,841.12812

In [38]:
y_pred = predictor.predict(test_data.drop(columns=[label]))
y_pred.head()
print(y_pred)

0      422.984833
1      430.485474
2      433.273712
3      476.895477
4     2060.780029
         ...
59      68.002571
60    1825.923828
61     431.161377
62      73.085846
63    1123.552490
Name: materialDensity, Length: 64, dtype: float32

In [47]:
combineY = pd.DataFrame ({
    'Y_test' : Y_test,
    'y_pred' : y_pred})

combineY.to_excel("Result_Enemble Model.xlsx")

In [20]:
predictor.evaluate(test_data, silent=True)

{'root_mean_squared_error': -127.69138768788623,
 'mean_squared_error': -16305.090489658065,
 'mean_absolute_error': -77.61031779412227,
 'r2': 0.9653380646575533,
 'pearsonr': 0.9829266141464504,
 'median_absolute_error': -40.0275457553828}

In [22]:
leaderboard = predictor.leaderboard(test_data, silent=True)

for index, row in leaderboard.iterrows():
    print(f"Model {index+1}:")
    print(row.to_dict())  # This prints the row details for each model

Model 1:
{'model': 'XGBoost_BAG_L1', 'score_test': -112.48260316084196, 'score_val': -164.574959493978, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.15964078903198242, 'pred_time_val': 0.034101009368896484, 'fit_time': 1.2717936038970947, 'pred_time_test_marginal': 0.15964078903198242, 'pred_time_val_marginal': 0.034101009368896484, 'fit_time_marginal': 1.2717936038970947, 'stack_level': 1, 'can_infer': True, 'fit_order': 4}
Model 2:
{'model': 'LightGBMLarge_BAG_L1', 'score_test': -121.64776206591759, 'score_val': -152.08548411439855, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.0630648136138916, 'pred_time_val': 0.023510217666625977, 'fit_time': 2.751824378967285, 'pred_time_test_marginal': 0.0630648136138916, 'pred_time_val_marginal': 0.023510217666625977, 'fit_time_marginal': 2.751824378967285, 'stack_level': 1, 'can_infer': True, 'fit_order': 6}
Model 3:
{'model': 'WeightedEnsemble_L3', 'score_test': -127.69138768788623, 'score_val': -133.96152653508557, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.8256793022155762, 'pred_time_val': 0.44039368629455566, 'fit_time': 297.17413353919983, 'pred_time_test_marginal': 0.003582000732421875, 'pred_time_val_marginal': 0.000978708267211914, 'fit_time_marginal': 0.008021116256713867, 'stack_level': 3, 'can_infer': True, 'fit_order': 14}
Model 4:
{'model': 'WeightedEnsemble_L2', 'score_test': -127.86801092883847, 'score_val': -134.5099901619082, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.571519136428833, 'pred_time_val': 0.2537956237792969, 'fit_time': 283.6248252391815, 'pred_time_test_marginal': 0.012508869171142578, 'pred_time_val_marginal': 0.0, 'fit_time_marginal': 0.008992195129394531, 'stack_level': 2, 'can_infer': True, 'fit_order': 7}
Model 5:
{'model': 'CatBoost_BAG_L1', 'score_test': -135.0608867383208, 'score_val': -157.51191203161832, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.0900728702545166, 'pred_time_val': 0.0336308479309082, 'fit_time': 261.41455721855164, 'pred_time_test_marginal': 0.0900728702545166, 'pred_time_val_marginal': 0.0336308479309082, 'fit_time_marginal': 261.41455721855164, 'stack_level': 1, 'can_infer': True, 'fit_order': 3}
Model 6:
{'model': 'LightGBMLarge_BAG_L2', 'score_test': -138.23513941999013, 'score_val': -160.5762266266345, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.5990910530090332, 'pred_time_val': 0.27494001388549805, 'fit_time': 285.4300391674042, 'pred_time_test_marginal': 0.04008078575134277, 'pred_time_val_marginal': 0.021144390106201172, 'fit_time_marginal': 1.8142061233520508, 'stack_level': 2, 'can_infer': True, 'fit_order': 13}
Model 7:
{'model': 'XGBoost_BAG_L2', 'score_test': -140.41218068337164, 'score_val': -157.6882828679788, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.6716141700744629, 'pred_time_val': 0.2895345687866211, 'fit_time': 284.6522557735443, 'pred_time_test_marginal': 0.11260390281677246, 'pred_time_val_marginal': 0.03573894500732422, 'fit_time_marginal': 1.0364227294921875, 'stack_level': 2, 'can_infer': True, 'fit_order': 11}
Model 8:
{'model': 'LightGBM_BAG_L1', 'score_test': -141.70249936022114, 'score_val': -147.742419194743, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.052062034606933594, 'pred_time_val': 0.023509740829467773, 'fit_time': 2.268571138381958, 'pred_time_test_marginal': 0.052062034606933594, 'pred_time_val_marginal': 0.023509740829467773, 'fit_time_marginal': 2.268571138381958, 'stack_level': 1, 'can_infer': True, 'fit_order': 1}
Model 9:
{'model': 'LightGBMXT_BAG_L2', 'score_test': -151.57439097821415, 'score_val': -162.80179362828972, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.6796200275421143, 'pred_time_val': 0.2753031253814697, 'fit_time': 284.69676971435547, 'pred_time_test_marginal': 0.12060976028442383, 'pred_time_val_marginal': 0.02150750160217285, 'fit_time_marginal': 1.0809366703033447, 'stack_level': 2, 'can_infer': True, 'fit_order': 9}
Model 10:
{'model': 'LightGBM_BAG_L2', 'score_test': -152.10137361929714, 'score_val': -166.7126458201449, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.6760351657867432, 'pred_time_val': 0.27786874771118164, 'fit_time': 284.31868052482605, 'pred_time_test_marginal': 0.11702489852905273, 'pred_time_val_marginal': 0.024073123931884766, 'fit_time_marginal': 0.7028474807739258, 'stack_level': 2, 'can_infer': True, 'fit_order': 8}
Model 11:
{'model': 'CatBoost_BAG_L2', 'score_test': -153.86722970436486, 'score_val': -170.0182665324567, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.6621217727661133, 'pred_time_val': 0.2817671298980713, 'fit_time': 392.5124888420105, 'pred_time_test_marginal': 0.10311150550842285, 'pred_time_val_marginal': 0.027971506118774414, 'fit_time_marginal': 108.89665579795837, 'stack_level': 2, 'can_infer': True, 'fit_order': 10}
Model 12:
{'model': 'LightGBMXT_BAG_L1', 'score_test': -155.5649406054929, 'score_val': -158.19512225708235, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.09758949279785156, 'pred_time_val': 0.024008750915527344, 'fit_time': 4.883697509765625, 'pred_time_test_marginal': 0.09758949279785156, 'pred_time_val_marginal': 0.024008750915527344, 'fit_time_marginal': 4.883697509765625, 'stack_level': 1, 'can_infer': True, 'fit_order': 2}
Model 13:
{'model': 'NeuralNetTorch_BAG_L2', 'score_test': -162.68068399641393, 'score_val': -175.1640322222653, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.6694126129150391, 'pred_time_val': 0.38253164291381836, 'fit_time': 294.3154835700989, 'pred_time_test_marginal': 0.11040234565734863, 'pred_time_val_marginal': 0.12873601913452148, 'fit_time_marginal': 10.699650526046753, 'stack_level': 2, 'can_infer': True, 'fit_order': 12}
Model 14:
{'model': 'NeuralNetTorch_BAG_L1', 'score_test': -205.7496251333704, 'score_val': -214.50800539986625, 'eval_metric': 'root_mean_squared_error', 'pred_time_test': 0.09658026695251465, 'pred_time_val': 0.1150350570678711, 'fit_time': 11.025389194488525, 'pred_time_test_marginal': 0.09658026695251465, 'pred_time_val_marginal': 0.1150350570678711, 'fit_time_marginal': 11.025389194488525, 'stack_level': 1, 'can_infer': True, 'fit_order': 5}